### PR TITLE
Add query range check (#471)

### PR DESCRIPTION
**Pull request by CaedenPH**
## Description:

- Tasks solved
  Add query range check
  - Link to respective files
       https://github.com/gleitz/howdoi/blob/master/howdoi/howdoi.py
       https://github.com/gleitz/howdoi/blob/master/test_howdoi.py
- Links to issues solved
    #471 

## Pull Request type:

- [ ] Bug fixes
- [x] New feature
- [ ] Improvement
- [ ] Refactoring
- [ ] Documentation update
- [ ] Security fix

## How to test:
```sh
>>> python -m howdoi a
ERROR: Please make a valid query
```

Please provide detailed instructions for testing your changes locally, including expected response/behavior.

```py
def test_query_length(self):
        self.assertIn("Please make a valid query", howdoi.howdoi("a"))
```
Any one word query with less than 2 letters should error

## Pull Request checklist:

- [x] Read the [contributing_to_howdoi.md](https://github.com/gleitz/howdoi/blob/master/docs/contributing_to_howdoi.md)
- [x] Attach screenshots of expected behavior.
- [x] The changes pass tests locally (`nose2`).
- [x] There are no linting errors (`python setup.py lint`).
- [x] The changes don't break existing features.
- [x] Check that there are no confidential files like `.env` included.
- [x] Request review from the maintainers.
- [x] For bug fixes or changes to directory structure, make sure docs are updated.

image

### CODE REVIEW

**Comment by CaedenPH** [comment]
@gleitz Pinging for review

**Comment by CaedenPH** [comment]
@gleitz 
The first commit was a mistake :eyes: 
Apologies

**Comment by gleitz** [comment]
What do you think about the tradeoffs between putting the check inside the `howdoi` function, vs a check on the [argparse library](https://stackoverflow.com/a/58977090/305414)?

If someone _really_ wanted to look up `howdoi c` (perhaps for c programming) should we allow that?

**Comment by CaedenPH** [comment]
> What do you think about the tradeoffs between putting the check inside the `howdoi` function, vs a check on the [argparse library](https://stackoverflow.com/a/58977090/305414)?
> 
> 
> 
> If someone _really_ wanted to look up `howdoi c` (perhaps for c programming) should we allow that?

What is the output of `howdoi c`? Does it actually provide a useful output?

**Comment by gleitz** [comment]
At the moment it's not very useful. It was more of a question of whether we want to put this range check at the command line level with argparse, and allowing any people who use howdoi as a library to continue to do so without limitations.

In practice it probably doesn't matter, just an interesting philosophical question of command line vs. library level range checks.

**Comment by CaedenPH** [comment]
> At the moment it's not very useful. It was more of a question of whether we want to put this range check at the command line level with argparse, and allowing any people who use howdoi as a library to continue to do so without limitations.
> 
> 
> 
> In practice it probably doesn't matter, just an interesting philosophical question of command line vs. library level range checks.
> 
> 
> 
> 

Ah, I see what you mean. Now that you raise the point, I think command line would actually be better to allow for more library control

**Pull request closed without merging**
