### PR TITLE
Requirement Files 

### PR DESCRIPTION
**Pull request by hmanalai**
- This PR fixes issue #293 by adding a requirements folder that contains three different .txt files for common/development/production specific requirements.

### CODE REVIEW

**Comment by gleitz** [comment]
Thanks for this. What do you think about linking `pip install -r requirements.txt` to `requirements/prod.txt` so we don't have any duplication?

**Comment by hmanalai** [comment]
I believe this change would need to happen in the python.yml file?

**Comment by gleitz** [comment]
I'm not sure about that yml file. Do you have a link to that usage? 

I think by default most people do `pip install -r requirements.txt` so I wanted to avoid having to update requirements in multiple places.

**Comment by gleitz** [comment]
So my ask would be to edit the requirements.txt file to point to your new prod.txt file.

**Comment by hmanalai** [comment]
I updated requirements.txt and tested it to make sure it works. Now it runs `-r requirements/prod.txt`.

**Comment by gleitz** [comment]
Thanks!

**Pull request merged**
