### PR TITLE
fit new stackoverflow css class

### PR DESCRIPTION
**Pull request by WindSoilder**
Fixes: #310 
This issue is because `stackoverflow` have change the answer node relative `class`.  And we can't find `.post-text` anymore.

### CODE REVIEW

**Comment by WindSoilder** [comment]
The UT runs into failed... I need to take more time to figure out what's going on here.. sorry for the disturb.

**Comment by WindSoilder** [comment]
Sometimes stackoverflow will return answer body with class `js-post-body` rather than `post-tag`.   
图片
So this PR will try to detect the class of answer body node first.

For the `js-post-body` case, I have tried to use it in another repo (here is the relative [PR](https://github.com/WindSoilder/hors/pull/88/files)), and it works fine for me :-)

**Comment by gleitz** [comment]
Thank you for this!

**Comment by gleitz** [comment]
I'm realizing that this change requires a clearing of the cache with `-C` to get answers that you've already searched for to appear with the `-a` flag instead of saying `Sorry, couldn't find any help with that topic`. I think we might need to version the FileSystemCache when we find breaking changes like this...

**Comment by gleitz** [comment]
Actually, I stand corrected. We already [version the cache key](https://github.com/gleitz/howdoi/blob/master/howdoi/howdoi.py#L453-L454) with the semantic version of the application so when I bump it we should be good to go!

**Pull request merged**
