### PR TITLE
update formula to work with linuxbrew

### PR DESCRIPTION
**Pull request by emanresusername**
i assume it'd also work with regular homebrew... but couldn't test that :thinking: 
would you want to keep maintaining it here, or turn it over to the homebrew repo? 
(or is it already maintained in a different tap somewhere that slipped under my radar?)

### CODE REVIEW

**Comment by gleitz** [comment]
The last time I looked into this, Homebrew did not want to host things that were also available via `pip` (see [here](https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Formulae.md)), so I decided to host my own formula.
Thanks for updating this. I would like to test this formula with regular homebrew just to make sure it works.

**Comment by emanresusername** [comment]
oh interesting, i didn't know the history 
well if the formulas i was looking at when i remembered this are any indication ([magic-wormhole](https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/magic-wormhole.rb#L2) and [mitmproxy](https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/mitmproxy.rb#L199)) 
looks like that policy might've changed

idk if the `virtualenv` stuff is a relatively recent development, 
i could imagine some cases against using homebrew to install a bunch of stuff with to the same global `pip` without the `virtualenv`s :thinking: 

in any case, yeah, lmk if it works with regular homebrew

**Comment by gleitz** [comment]
Just installed this on a mac and it worked, so I think we're all good to go. Thx!

**Comment by emanresusername** [comment]
dope 👌 
i'll raise an issue with homebrew-core and reference this and see if they want to take the maintenance under their wing ...

**Comment by emanresusername** [comment]
@gleitz it's in homebrew-core officially now https://github.com/Homebrew/homebrew-core/commit/5aefbfe9fe2b488cb39815dc70ea96a947a20006

**Pull request merged**
