### PR TITLE
Include urls by default.

### PR DESCRIPTION
**Pull request by jericson**
Addresses https://github.com/gleitz/howdoi/issues/152

### CODE REVIEW

**Comment by gleitz** [comment]
Thanks @jericson.

I wonder if we should use `//` to preface the URL instead of surrounding it with `---` as it will be more likely to already be in comment form.

**Comment by jericson** [comment]
That seems reasonable too. I was also thinking of `#`, but the important thing is to separate it from the answer somehow. (Text is tricky!)

**Comment by GabLeRoux** [comment]
What about some special character?

    echo '\u2605'
    ★

Since results may already have comments (which differs from languages to languages).

**Comment by tra38** [comment]
Any move on merging in this PR into master?

**Comment by gleitz** [comment]
Closed in favor of #169

**Pull request closed without merging**
