### PR TITLE
fix bug in howdoi() function

### LINKED ISSUE #363: [BUG] Program crashes if engine rejects howdoi
```
Traceback (most recent call last):                                                                                                                                     
  File "/home/adb/.venvs/py38/bin/howdoi", line 8, in <module>                                                                                                        
    sys.exit(command_line_runner())                                                                                                                                    
  File "/home/adb/.venvs/py38/lib/python3.8/site-packages/howdoi/howdoi.py", line 757, in command_line_runner
    utf8_result = howdoi(args).encode('utf-8', 'ignore')                                                                                                               
  File "/home/adb/.venvs/py38/lib/python3.8/site-packages/howdoi/howdoi.py", line 578, in howdoi                                                                      
    return _parse_cmd(args, res)                                                                                                                                       
  File "/home/adb/.venvs/py38/lib/python3.8/site-packages/howdoi/howdoi.py", line 540, in _parse_cmd                                                                  
    answer = _format_answers(args, res)                                                                                                                                
  File "/home/adb/.venvs/py38/lib/python3.8/site-packages/howdoi/howdoi.py", line 458, in _format_answers
    next_ans = answer["answer"]                                                                                                                                        
TypeError: string indices must be integers
```

### PR DESCRIPTION
**Pull request by adbenitez**
on connection exception, return dict instead of set.

close #363

### CODE REVIEW

**Comment by gleitz** [comment]
Wow, nice catch! Is there a way to reproduce the error? I didn't see a query in the big report (or if you need to be off WiFi or whatever)

**Comment by adbenitez** [comment]
I experienced the error in some VPS where I have a bot (similar to Telegram howdoi bot, but for DeltaChat app) it is not related to the query but to the engine detecting some VPS IPs or so, and not happy with machines doing queries

**Comment by adbenitez** [comment]
the issue is particularly with Google, I switched to DuckDuckGo

**Comment by gleitz** [comment]
Yes, Google is often blocked on VPS so it's a good choice to switch to another engine.

**Pull request merged**
