### PR TITLE
allow to execute module with python -m

### PR DESCRIPTION
**Pull request by adbenitez**

### CODE REVIEW

**Comment by gleitz** [comment]
Today you can run the application in development using the command 

```
python -m howdoi.howdoi format date bash
```

With this PR, how will that change?

**Comment by adbenitez** [comment]
it still will work

**Comment by adbenitez** [comment]
but you can use now the shorter `python -m howdoi format date bash`

**Comment by gleitz** [comment]
Cool, thx!

**Comment by gleitz** [comment]
Updated the documentation in https://github.com/gleitz/howdoi/commit/f7f6333fb22fae7c4e895ef396b0739562ac7fac

**Pull request merged**
